# SPDX-License-Identifier: GPL-2.0
#
# Makefile for HPE SoC drivers
#

obj-$(CONFIG_SOC_HPE_GXP)		+= gxp-soclib.o
obj-$(CONFIG_SOC_HPE_GXP_CSM)		+= gxp-csm.o
obj-$(CONFIG_SOC_HPE_GXP_XREG)		+= gxp-xreg.o
obj-$(CONFIG_SOC_HPE_GXP_FN2)		+= gxp-fn2.o
obj-$(CONFIG_SOC_HPE_GXP_POWER_CTRL)	+= gxp-power-ctrl.o
obj-$(CONFIG_SOC_HPE_GXP_CHIF)		+= gxp-chif.o
