# SPDX-License-Identifier: GPL-2.0
# temporary disable, later add different config for gen10 and gen11
# 
dtb-$(CONFIG_ARCH_HPE_GXP) += \
	hpe-bmc-dl360gen10.dtb
dtb-$(CONFIG_ARCH_HPE_GXP) += \
	hpe-bmc-gen11.dtb
